name: Create an issue

on:
  workflow_dispatch:

jobs:
  create_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Get today's date
        id: date
        run: |
          echo "::set-output name=today::$(date "+%Y/%m/%d")"

      - name: Create an issue
        uses: actions-ecosystem/action-create-issue@v1
        with:
          github_token: ${{ secrets.PAT_TOKEN }}
          title: ${{ steps.date.outputs.today }}
          body: |
            ## This today's TODO

            - [ ] testing
            - [ ] Check the dashboard

          labels: |
            meeting
            weekly
    
      - name: Create Issue
        uses: dacbd/create-issue-action@v1
        with:
          token: ${{ secrets.PAT_TOKEN }}
          owner: kingdom-tower
          repo: playground-2
          title: ${{ steps.date.outputs.today }}
          body: |
            ## This today's TODO

      - name: Create Issue
        uses: dacbd/create-issue-action@v1
        with:
          token: ${{ secrets.PAT_TOKEN_EXTERNAL }}
          owner: cpanato
          repo: testing-ci-private
          title: ${{ steps.date.outputs.today }}
          body: |
            ## This today's TODO


            - [ ] testing
            - [ ] Check the dashboard
